import { useState, useMemo } from "react";

interface JournalEntry { date?: string; time: string; text: string; focusIndex: number; mood: string[]; }
interface MedRow { date: string; time: string; name: string; dose: string; }
interface TaskRow { title: string; done: boolean; createdAt?: string; focusRequired?: number; estimatedMinutes: number | null; }
interface SessionRow { date: string; time: string; taskTitle: string | null; minutes: number; }

const UI = {
  en: {
    title: "Focus & Activity Report", subtitle: "Generated by Tokai · Neurosupportive Productivity",
    patient: "Patient", email: "Email", range: "Date range", generated: "Generated",
    range7: "Last 7 days", range30: "Last 30 days", range90: "Last 90 days", rangeAll: "All time",
    disclaimer: "This report is for informational and self-tracking purposes only and is not a diagnostic tool. Neural metrics in this alpha release are simulated, not measured from EEG hardware — the behavioral data (medications, journal, mood, task completion, and focus sessions) reflects the user's own entries. Please interpret alongside clinical judgment.",
    summary: "Summary", avgFocus: "Avg focus (journaled)", journalEntries: "Journal entries",
    focusSessions: "Focus sessions", focusMinutes: "Focus minutes", tasksDone: "Tasks completed", medsLogged: "Meds logged",
    focusTrend: "Self-reported focus over time", day: "Day", entries: "Entries", avg: "Avg focus", noData: "No data in this range.",
    medsHdr: "Medication & supplement log", med: "Medication", dose: "Dose", whenH: "When",
    moodHdr: "Journal & mood", moods: "Moods", note: "Note", focus: "Focus",
    sessionsHdr: "Focus sessions (TokTimer)", blocks: "Blocks", minutes: "Minutes", topTask: "Top task",
    tasksHdr: "Tasks", completion: "Completion", reqDone: "Avg focus required (done)", reqPending: "Avg focus required (pending)",
    insightsHdr: "Automatic observations (TokInsights)",
    print: "Print / Save PDF", close: "Close", page: "Tokai — tokai.app",
  },
  zh: {
    title: "專注與活動報告", subtitle: "由 Tokai 生成 · 神經支持型生產力",
    patient: "使用者", email: "電子郵件", range: "日期範圍", generated: "生成時間",
    range7: "最近 7 天", range30: "最近 30 天", range90: "最近 90 天", rangeAll: "全部",
    disclaimer: "本報告僅供資訊與自我追蹤用途，並非診斷工具。此 Alpha 版本中的神經指標為模擬數據，並非由 EEG 硬體量測；行為數據（用藥、日誌、情緒、任務完成與專注時段）反映使用者本人的紀錄。請與臨床判斷一併解讀。",
    summary: "摘要", avgFocus: "平均專注（日誌）", journalEntries: "日誌條目",
    focusSessions: "專注時段", focusMinutes: "專注分鐘", tasksDone: "已完成任務", medsLogged: "用藥紀錄",
    focusTrend: "自述專注趨勢", day: "日期", entries: "條目", avg: "平均專注", noData: "此範圍內無資料。",
    medsHdr: "藥物與補充品紀錄", med: "藥物", dose: "劑量", whenH: "時間",
    moodHdr: "日誌與情緒", moods: "情緒", note: "筆記", focus: "專注",
    sessionsHdr: "專注時段（TokTimer）", blocks: "時段數", minutes: "分鐘", topTask: "主要任務",
    tasksHdr: "任務", completion: "完成率", reqDone: "平均所需專注（已完成）", reqPending: "平均所需專注（未完成）",
    insightsHdr: "自動觀察（TokInsights）",
    print: "列印／儲存 PDF", close: "關閉", page: "Tokai — tokai.app",
  },
};

const C = { ink: "#1a2230", line: "#d8dde6", accent: "#7c3aed", soft: "#f4f1fb", bg: "#ffffff" };

export default function ClinicianReport({ name, email, lang = "en", journal, meds, tasks, sessions, insights, onClose }: {
  name: string; email: string; lang?: "en" | "zh";
  journal: JournalEntry[]; meds: MedRow[]; tasks: TaskRow[]; sessions: SessionRow[];
  insights: { icon: string; text: string }[];
  onClose: () => void;
}) {
  const t = UI[lang];
  const [days, setDays] = useState<number>(30); // 0 = all

  // Print from a clean static popup so the live-updating dashboard can't disrupt the PDF capture.
  function printReport() {
    const node = document.getElementById("clinician-report");
    if (!node) return;
    const w = window.open("", "tokai-report", "width=920,height=1000");
    if (!w) { window.print(); return; } // popup blocked → fall back to in-page print
    w.document.write(
      `<!DOCTYPE html><html lang="${lang}"><head><meta charset="utf-8" />` +
      `<title>Tokai — ${t.title}</title>` +
      `<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>` +
      `<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">` +
      `<style>html,body{margin:0;background:#fff;font-family:'Inter',system-ui,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact;}@page{margin:1.4cm;}#clinician-report{box-shadow:none!important;border-radius:0!important;}</style>` +
      `</head><body>${node.outerHTML}</body></html>`
    );
    w.document.close();
    const go = () => { try { w.focus(); w.print(); } catch { /* ignore */ } };
    w.onload = go;
    setTimeout(go, 500); // fallback if onload already fired
  }

  const from = useMemo(() => days === 0 ? "0000-00-00" : new Date(Date.now() - days * 86400000).toISOString().slice(0, 10), [days]);
  const inRange = (d?: string) => !!d && d.slice(0, 10) >= from;

  const jr = journal.filter(e => inRange(e.date));
  const mr = meds.filter(m => inRange(m.date));
  const sr = sessions.filter(s => inRange(s.date));
  const tr = tasks.filter(tk => inRange(tk.createdAt));

  const round = (n: number) => Math.round(n);
  const mean = (a: number[]) => a.length ? a.reduce((x, y) => x + y, 0) / a.length : 0;

  // Daily focus from journal
  const byDay: Record<string, number[]> = {};
  for (const e of jr) { const d = (e.date ?? "").slice(0, 10); (byDay[d] ??= []).push(e.focusIndex); }
  const days_sorted = Object.keys(byDay).sort().reverse();
  const avgFocusAll = round(mean(jr.map(e => e.focusIndex)));

  const totalMin = sr.reduce((a, s) => a + s.minutes, 0);
  const tasksDone = tr.filter(tk => tk.done).length;
  const doneReq = tr.filter(tk => tk.done && tk.focusRequired != null).map(tk => tk.focusRequired as number);
  const pendReq = tr.filter(tk => !tk.done && tk.focusRequired != null).map(tk => tk.focusRequired as number);

  // Sessions by day
  const sessByDay: Record<string, { count: number; min: number; tasks: Record<string, number> }> = {};
  for (const s of sr) { const b = (sessByDay[s.date] ??= { count: 0, min: 0, tasks: {} }); b.count++; b.min += s.minutes; if (s.taskTitle) b.tasks[s.taskTitle] = (b.tasks[s.taskTitle] || 0) + s.minutes; }

  const now = new Date();
  const th: React.CSSProperties = { textAlign: "left", padding: "6px 8px", borderBottom: `2px solid ${C.line}`, color: C.accent, fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.5 };
  const td: React.CSSProperties = { padding: "6px 8px", borderBottom: `1px solid ${C.line}`, fontSize: 13, color: C.ink, verticalAlign: "top" };
  const h2: React.CSSProperties = { fontSize: 15, fontWeight: 700, color: C.accent, margin: "22px 0 8px", borderBottom: `1px solid ${C.line}`, paddingBottom: 4, letterSpacing: 0.3 };

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", zIndex: 500, overflowY: "auto", padding: 24, fontFamily: "'Inter', system-ui, sans-serif" }}>
      {/* Controls */}
      <div className="no-print" style={{ maxWidth: 820, margin: "0 auto 12px", display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
        <div style={{ display: "flex", gap: 6 }}>
          {([[7, t.range7], [30, t.range30], [90, t.range90], [0, t.rangeAll]] as [number, string][]).map(([d, label]) => (
            <button key={d} onClick={() => setDays(d)}
              style={{ padding: "7px 12px", borderRadius: 6, border: `1px solid ${days === d ? "#c084fc" : "rgba(255,255,255,0.3)"}`, background: days === d ? "rgba(192,132,252,0.25)" : "rgba(255,255,255,0.08)", color: "#fff", fontSize: 12, cursor: "pointer" }}>{label}</button>
          ))}
        </div>
        <div style={{ marginLeft: "auto", display: "flex", gap: 8 }}>
          <button onClick={printReport} style={{ padding: "8px 16px", borderRadius: 6, border: "1px solid #c084fc", background: "#7c3aed", color: "#fff", fontSize: 13, fontWeight: 600, cursor: "pointer" }}>{t.print}</button>
          <button onClick={onClose} style={{ padding: "8px 16px", borderRadius: 6, border: "1px solid rgba(255,255,255,0.3)", background: "rgba(255,255,255,0.08)", color: "#fff", fontSize: 13, cursor: "pointer" }}>{t.close}</button>
        </div>
      </div>

      {/* The printable report */}
      <div id="clinician-report" style={{ maxWidth: 820, margin: "0 auto", background: C.bg, color: C.ink, borderRadius: 10, padding: "32px 36px", boxShadow: "0 10px 40px rgba(0,0,0,0.4)" }}>
        {/* Header */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, borderBottom: `2px solid ${C.accent}`, paddingBottom: 14 }}>
          <div>
            <div style={{ fontSize: 24, fontWeight: 800, letterSpacing: 1, color: C.accent }}>TOKAI</div>
            <div style={{ fontSize: 16, fontWeight: 700, marginTop: 4 }}>{t.title}</div>
            <div style={{ fontSize: 11, color: "#6b7280" }}>{t.subtitle}</div>
          </div>
          <div style={{ fontSize: 12, color: "#374151", textAlign: "right", lineHeight: 1.7 }}>
            <div><strong>{t.patient}:</strong> {name || "—"}</div>
            <div><strong>{t.email}:</strong> {email}</div>
            <div><strong>{t.range}:</strong> {days === 0 ? t.rangeAll : (lang === "en" ? `Last ${days} days` : `最近 ${days} 天`)}</div>
            <div><strong>{t.generated}:</strong> {now.toISOString().slice(0, 10)} {now.toTimeString().slice(0, 5)}</div>
          </div>
        </div>

        {/* Disclaimer */}
        <div style={{ marginTop: 12, padding: "10px 12px", background: C.soft, border: `1px solid ${C.line}`, borderRadius: 6, fontSize: 11.5, color: "#4b5563", lineHeight: 1.6 }}>
          ⚠ {t.disclaimer}
        </div>

        {/* Summary */}
        <div style={h2}>{t.summary}</div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 10 }}>
          {[
            [t.avgFocus, jr.length ? `${avgFocusAll}/100` : "—"],
            [t.journalEntries, String(jr.length)],
            [t.medsLogged, String(mr.length)],
            [t.focusSessions, String(sr.length)],
            [t.focusMinutes, String(totalMin)],
            [t.tasksDone, `${tasksDone}/${tr.length}`],
          ].map(([label, val]) => (
            <div key={label} style={{ border: `1px solid ${C.line}`, borderRadius: 6, padding: "10px 12px" }}>
              <div style={{ fontSize: 20, fontWeight: 800, color: C.accent }}>{val}</div>
              <div style={{ fontSize: 11, color: "#6b7280", marginTop: 2 }}>{label}</div>
            </div>
          ))}
        </div>

        {/* Focus trend */}
        <div style={h2}>{t.focusTrend}</div>
        {days_sorted.length === 0 ? <div style={{ fontSize: 13, color: "#9ca3af" }}>{t.noData}</div> : (
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead><tr><th style={th}>{t.day}</th><th style={th}>{t.entries}</th><th style={th}>{t.avg}</th><th style={{ ...th, width: "45%" }} /></tr></thead>
            <tbody>{days_sorted.map(d => { const a = round(mean(byDay[d])); return (
              <tr key={d}><td style={td}>{d}</td><td style={td}>{byDay[d].length}</td><td style={td}>{a}/100</td>
                <td style={td}><div style={{ height: 8, background: C.line, borderRadius: 4, overflow: "hidden" }}><div style={{ width: `${a}%`, height: "100%", background: C.accent }} /></div></td></tr>
            ); })}</tbody>
          </table>
        )}

        {/* Medications */}
        <div style={h2}>{t.medsHdr}</div>
        {mr.length === 0 ? <div style={{ fontSize: 13, color: "#9ca3af" }}>{t.noData}</div> : (
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead><tr><th style={th}>{t.whenH}</th><th style={th}>{t.med}</th><th style={th}>{t.dose}</th></tr></thead>
            <tbody>{mr.slice().reverse().map((m, i) => (
              <tr key={i}><td style={td}>{m.date} {m.time}</td><td style={td}>{m.name}</td><td style={td}>{m.dose || "—"}</td></tr>
            ))}</tbody>
          </table>
        )}

        {/* Focus sessions */}
        <div style={h2}>{t.sessionsHdr}</div>
        {Object.keys(sessByDay).length === 0 ? <div style={{ fontSize: 13, color: "#9ca3af" }}>{t.noData}</div> : (
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead><tr><th style={th}>{t.day}</th><th style={th}>{t.blocks}</th><th style={th}>{t.minutes}</th><th style={th}>{t.topTask}</th></tr></thead>
            <tbody>{Object.keys(sessByDay).sort().reverse().map(d => { const b = sessByDay[d]; const top = Object.entries(b.tasks).sort((x, y) => y[1] - x[1])[0]; return (
              <tr key={d}><td style={td}>{d}</td><td style={td}>{b.count}</td><td style={td}>{b.min}</td><td style={td}>{top ? `${top[0]} (${top[1]}m)` : "—"}</td></tr>
            ); })}</tbody>
          </table>
        )}

        {/* Tasks */}
        <div style={h2}>{t.tasksHdr}</div>
        <div style={{ display: "flex", gap: 24, fontSize: 13, flexWrap: "wrap" }}>
          <div><strong>{t.completion}:</strong> {tr.length ? `${tasksDone}/${tr.length} (${round(tasksDone / tr.length * 100)}%)` : "—"}</div>
          {doneReq.length > 0 && <div><strong>{t.reqDone}:</strong> {round(mean(doneReq))}/100</div>}
          {pendReq.length > 0 && <div><strong>{t.reqPending}:</strong> {round(mean(pendReq))}/100</div>}
        </div>

        {/* Mood & journal */}
        <div style={h2}>{t.moodHdr}</div>
        {jr.length === 0 ? <div style={{ fontSize: 13, color: "#9ca3af" }}>{t.noData}</div> : (
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead><tr><th style={th}>{t.whenH}</th><th style={th}>{t.focus}</th><th style={th}>{t.moods}</th><th style={{ ...th, width: "45%" }}>{t.note}</th></tr></thead>
            <tbody>{jr.slice().reverse().slice(0, 40).map((e, i) => (
              <tr key={i}><td style={td}>{(e.date ?? "").slice(0, 10)} {e.time}</td><td style={td}>{round(e.focusIndex)}</td>
                <td style={td}>{(e.mood || []).join(", ") || "—"}</td>
                <td style={td}>{e.text.length > 120 ? e.text.slice(0, 120) + "…" : e.text}</td></tr>
            ))}</tbody>
          </table>
        )}

        {/* Insights */}
        {insights.length > 0 && (<>
          <div style={h2}>{t.insightsHdr}</div>
          <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13, lineHeight: 1.7 }}>
            {insights.map((ins, i) => <li key={i}>{ins.text}</li>)}
          </ul>
        </>)}

        <div style={{ marginTop: 26, paddingTop: 10, borderTop: `1px solid ${C.line}`, fontSize: 11, color: "#9ca3af", display: "flex", justifyContent: "space-between" }}>
          <span>{t.page}</span><span>{name || email}</span>
        </div>
      </div>
    </div>
  );
}
